- name: install requirements
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - openjdk-14-jdk-headless
    state: present

- name: import elasticsarch repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: setup elasticsarch apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_apt_version }}/apt stable main"
    state: present
    filename: elasticsearch

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: template /etc/elasticsearch/elasticsearch.yml
  template:
    src: "templates/etc/elasticsearch/elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: 0640
  notify: restart elasticsearch

- name: template /etc/default/elasticsearch
  template:
    src: "templates/etc/default/elasticsearch.j2"
    dest: "/etc/default/elasticsearch"
    owner: root
    group: elasticsearch
    mode: 0640
  notify: restart elasticsearch
