- name: template /etc/elasticsearch/elasticsearch.yml
  template:
    src: "templates/etc/elasticsearch/elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: 0640
  notify: restart elasticsearch

- name: template /etc/default/elasticsearch
  template:
    src: "templates/etc/default/elasticsearch.j2"
    dest: "/etc/default/elasticsearch"
    owner: root
    group: elasticsearch
    mode: 0640
  notify: restart elasticsearch
